services:
  - type: web
    name: weather-dashboard
    env: node
    plan: free
    repo: https://github.com/PothulaAditya/weather-dashboard.git
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: OPENWEATHERMAP_API_KEY
        sync: false
